# Generated by Django 3.2 on 2025-08-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20250805_2114'),
        ('accounts', '0002_auto_20250809_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.category'),
        ),
    ]
